# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release: 
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x
        - name: Restore dependencies
          run: dotnet restore

        - name: Install pupnet
          run: dotnet tool install --global KuiperZone.PupNet

        - name: Create Setup 
          run: pupnet A2RacerTool --kind setup -y

        - name: Create Zip 
          run: pupnet A2RacerTool --kind zip -y

        - name: Upload a InnoSetup Artifact
          uses: actions/upload-artifact@v4.6.2
          with:
            name: A2RacerTool.x64.exe # optional, default is artifact
            path: ./A2RacerTool/Deploy/bin/A2RacerTool.x64.exe
            
        - name: Upload a .zip Artifact
          uses: actions/upload-artifact@v4.6.2
          with:
            name: A2RacerTool-1.0.0-1.win-x64.zip # optional, default is artifact
            path: ./A2RacerTool/Deploy/bin/A2RacerTool-1.0.0-1.win-x64.zip
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Install libfuse2t64
      run: sudo apt-get install -y libfuse2t64

    - name: Install pupnet
      run: dotnet tool install --global KuiperZone.PupNet
      
    - name: Create AppImage
      run: pupnet A2RacerTool --runtime linux-x64 --kind appimage -y
      
    - name: Create .RPM
      run: pupnet A2RacerTool --runtime linux-x64 --kind rpm -y
      
    - name: Create .DEB
      run: pupnet A2RacerTool --runtime linux-x64 --kind deb -y
      
    - name: Create .ZIP
      run: pupnet A2RacerTool --runtime linux-x64 --kind zip -y
    
    - name: Upload an AppImage Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: A2RacerTool.x86_64.AppImage # optional, default is artifact
        path: ./A2RacerTool/Deploy/bin/A2RacerTool.x86_64.AppImage
          
    - name: Upload a .deb Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: a2racertool_1.0.0-1_amd64.deb # optional, default is artifact
        path: ./A2RacerTool/Deploy/bin/a2racertool_1.0.0-1_amd64.deb # todo: add automatic versioning

    - name: Upload a .rpm Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: a2racertool_1.0.0-1.x86_64.rpm # optional, default is artifact
        path: ./A2RacerTool/Deploy/bin/a2racertool_1.0.0-1.x86_64.rpm # todo: add automatic versioning
    - name: Upload a .zip Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: A2RacerTool-1.0.0-1.linux-x64.zip # optional, default is artifact
        path: ./A2RacerTool/Deploy/bin/A2RacerTool.1.0.0-1.linux-x64.zip # todo: add automatic versioning
              
